ponder.version=1.1.2-mc1.12.2
ponder_mmce.version=0.1.0-alpha
mmce.version=2.3.2
crafttweaker.version=4.1.20.698
mixinbooter.version=11.2
static.machine=modularmachinery:ponder_mmce_static_demo
dynamic.machine=modularmachinery:ponder_mmce_dynamic_demo
unconfigured.machine=modularmachinery:ponder_mmce_unconfigured
